### ISSUE TITLE
Is the project dead??

### ISSUE THREAD

**Issue by projser** [SearchScale/dataimporthandler#31]
Is the project dead ... even the is simple questions are not answered.

Regards

Julio Gomes

**Comment by epugh** [comment]
It's not in a healthy place, and there is an opportunity for someone to come in and reboot this project.

**Comment by gmkey** [comment]
I am absolutely amazed how easily the SOLR project has ditched a widely used part of it's project and dumped it on the first person that said they would be willing to support it. Now I am no Java Dev so I can't be of much help, but I'd love to hear if others would support flagging this within the solr community.

**Comment by epugh** [comment]
This is always the interesting challenge with open source, which is that without a community actively maintaining the code, it becomes orphaned.    The DIH code was VERY much orphaned even when it was part of Apache Solr.  Lots of bugs, not much innovation.    So moving it out was an acknowledgement of that sad state of affairs.    

This project doesn't really need "developer support", instead it needs some community of people who are actively using DIH in their projects to form around this project.   Someone to start answering questions...   Someone to start triaging bug reports.   Maybe set up a Gitter account and answer questions.   With that, I suspect that new developers would show up who are using DIH and start contributing fixes again.

**Comment by MarcoRemy** [comment]
Here is the reason why it got removed:

> Deprecation notice
> ------------------
> This contrib module is deprecated as of v8.6, scheduled for removal in Solr 9.0.
> The reason is that DIH is no longer being maintained in a manner we feel is necessary in order to keep it
> healthy and secure. Also it was not designed to work with SolrCloud and does not meet current performance requirements.
> 
> The project hopes that the community will take over maintenance of DIH as a 3rd party package (See SOLR-14066 for more details). Please reach out to us at the dev@ mailing list if you want to help.

https://github.com/apache/solr/blob/releases/lucene-solr/8.6.0/solr/contrib/dataimporthandler/README.txt

**Comment by chatman** [comment]
Hi, the project has now a new home. https://lists.apache.org/thread/bmovqmy9gsg6fcfyl2oj6v2lft3x0jpq
