### ISSUE TITLE
Can we add release for latest solr 9.2.1

### ISSUE THREAD

**Issue by sajiljosephs** [SearchScale/dataimporthandler#41]
Can we add release for latest solr 9.2.1

Error:
bin/solr package deploy data-import-handler -y -collections products

Found 1 Solr nodes: 

Solr process 11 running on port 8983
Version incompatible! Solr version: 9.2.1, package version constraint: 9.0.0-9.0.99

**Comment by walecharohit** [comment]
any updates on this ??
if not, what else can we choose for imports ??

**Comment by walecharohit** [comment]
@sajiljosephs 
you can use my private [fork](https://github.com/walecharohit/data_import_handler).
I've added support for 9.2.1.
Please send a request I'll add you as collaborator.

**Comment by sajiljosephs** [comment]
@walecharohit  I am getting a 404 page

**Comment by chatman** [comment]
There's a PR here:
https://github.com/SearchScale/dataimporthandler/pull/45

Once we merge it, it should be available. I'll likely merge it by tomorrow
and initiate a release.

**Comment by walecharohit** [comment]
@chatman in branch [branch_9x](https://github.com/aadrian/dataimporthandler/tree/branch_9x) I can't see `repository.json` updated with 9.2.1.

**Comment by sajiljosephs** [comment]
@chatman  Any updates on this ? I am not able to specifically find any release for it.

**Comment by walecharohit** [comment]
@sajiljosephs I gave you access to my private [fork](https://github.com/walecharohit/data_import_handler).
You can try with this..until a release is done for 9.2.1.

**Comment by chatman** [comment]
@sajiljosephs @walecharohit version 9.2.1 is released. https://lists.apache.org/thread/sd6z98wt0gb9pjg7x19qynono7z52tnl

Thank you very much for your patience.

@walecharohit Rohit, would you like to volunteer as a maintainer for this project?

**Comment by rohitwalecha** [comment]
sure @chatman , Ishan..Please add me.
Thanks !! :)
