### ISSUE TITLE
FYI. Doesn't work in 9.4 either 

### ISSUE THREAD

**Issue by mkhludnev** [SearchScale/dataimporthandler#56]
1. I suppose that earlier reported 9.3 issues with content-type is fixed.
2. theses two issues seems like Solr side, not DIH's side. 
https://issues.apache.org/jira/browse/SOLR-17072 <- verify command path is wrong in repository.json
https://issues.apache.org/jira/browse/SOLR-17073 <- `-solrUrl` is mandatory on windows

**Comment by chatman** [comment]
Thanks, I'll take a look shortly.

**Comment by mkhludnev** [comment]
verify commands are wrong for 9.3 and 9.4, there are three errors in it
 `8.6 right "condition": "$['config'].['requestHandler'].['${RH-HANDLER-PATH}'].['_packageinfo_'].['version']",`
`9.3, 9.4 wrong "$[config].[requestHandler].[HANDLER-PATH].[_packageinfo_].[version]"`
