### ISSUE TITLE
Dataimport tab not present in Solr Admin

### ISSUE THREAD

**Issue by ruggiero-m** [SearchScale/dataimporthandler#66]
Dataimport tab not present in Solr Admin, how can I enable it?

![Schermata del 2024-01-26 16-26-41](https://github.com/SearchScale/dataimporthandler/assets/100686936/e5daf334-894f-4c4f-9fe9-360174c05765)

**Comment by ruggiero-m** [comment]
update: in production the tab is visible but there are js errors

![WhatsApp Image 2024-02-28 at 12 25 01](https://github.com/SearchScale/dataimporthandler/assets/100686936/217eb005-f2a7-4c97-b374-e5197ccc4615)

**Comment by chatman** [comment]
In 9x Solr, DIH tab is not available in the UI. Someone would need to add
support into the package management system for plugins to be able to add to
the admin UI. Otherwise, a completely standalone UI for DIH can be built.

**Comment by ruggiero-m** [comment]
Thank you @chatman, 
but reading the readme of this package it seems to be there: _(Solr Admin UI's Dataimport tab could be a bit glitchy when used with this package)_

![Schermata del 2024-02-28 14-28-45](https://github.com/SearchScale/dataimporthandler/assets/100686936/05b807bf-524d-4efd-a7fb-c997ea0ea678)

**Comment by chatman** [comment]
That applies to 8x Solr.

**Comment by ruggiero-m** [comment]
ok it's not clear that it refers to solr 8.
Thanks a lot!!!
